### ISSUE TITLE
How to support data parallel and model parallel for megatron at the same time.

### ISSUE THREAD

**Issue by superqing001** [laekov/fastmoe#105]
When using multi node and multi GPU, how to support data parallel and model parallel of Megatron at the same time.

**Comment by laekov** [comment]
In `FMoE`'s `_init_` is an argument named `moe_group`. Set it as the communicator of all workers in a node.
Then, in `DistributedGroupedDataParallel`, set `moe_group` as the prependicular communicator for data parallelism.

**Comment by superqing001** [comment]
I'll try, thank you.
