### ISSUE TITLE
AttributeError: module 'torch.autograd' has no attribute 'graph'

### ISSUE THREAD

**Issue by Fragile-azalea** [laekov/fastmoe#112]
**Describe the bug**
Hi dear author, when I try to use FastMoE, I find that my program aborts unexpectedly.
AttributeError: module 'torch.autograd' has no attribute 'graph'
https://github.com/laekov/fastmoe/blob/5083a7367f2defcf5e1022dcdce39022acf5ca11/fmoe/fastermoe/schedule.py#L37
This method seems to work only in Pytorch versions >=1.10. Am I understanding this correctly?

**To Reproduce**
1. pip setup.py install
2. cd tests
3. pytest .

**Expected behavior**
It seems that there is no package named 'torch.autograd.graph' in Pytorch 1.8.0.

**Platform**
 - Device: NVIDIA GeForce GTX 1080 Ti
 - OS: Ubuntu 16.04.6 LTS
 - CUDA version: 11.4
 - PyTorch version: 1.8.0

**Comment by laekov** [comment]
I think you are right. When developing these features, I was using PyTorch v1.10.0 and I did not test on older versions of PyTorch.

**Comment by laekov** [comment]
In PyTorch 1.8.0, you can simply remove the line of with (and correctindent of the following line). This should make everything fine.

**Comment by Fragile-azalea** [comment]
Thank you for your very helpful reply.
