### ISSUE TITLE
AssertionError: assert topk_val[i, j] == gate_score[i, v]

### ISSUE THREAD

**Issue by Fragile-azalea** [laekov/fastmoe#114]
**Describe the bug**
The test fails in test_gate.py.
https://github.com/laekov/fastmoe/blob/d3f71f211356bf8ab350982e73dcf45afc0c4fad/tests/test_gates.py#L53
The topk_val seems to be probs (i.e. after the top-k and softmax function).
The gate_score seems to be logits (i.e. before the softmax function).
**To Reproduce**
1.  cd tests
2. pytest test_gates.py 

**Expected behavior**
topk_val[i, j] == gate_score[i, v]

**Example**
An example is given to better understand this problem.
topk_idx:tensor([[ 3,  0],
        [ 3,  0],
        [-1, -1],
        [ 1, -1],
        [-1, -1],
        [-1,  2],
        [-1, -1],
        [-1,  1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1,  2],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]], device='cuda:0')
topk_val:tensor([[0.5074, 0.4926],
        [0.5396, 0.4604],
        [0.5462, 0.4538],
        [0.5081, 0.4919],
        [0.5264, 0.4736],
        [0.5338, 0.4662],
        [0.5150, 0.4850],
        [0.5240, 0.4760],
        [0.5507, 0.4493],
        [0.5500, 0.4500],
        [0.5912, 0.4088],
        [0.6057, 0.3943],
        [0.5083, 0.4917],
        [0.5173, 0.4827],
        [0.5245, 0.4755],
        [0.5367, 0.4633]], device='cuda:0', grad_fn=\<SoftmaxBackward\>)
gate_score:tensor([[ 0.2501, -0.0702, -0.1015,  0.2797],
        [ 0.1714, -0.1289,  0.0418,  0.3300],
        [-0.0527, -0.1758, -0.1488,  0.1325],
        [-0.0865,  0.1738, -0.1027,  0.1415],
        [ 0.0561, -0.2316, -0.3943,  0.1617],
        [ 0.0265, -0.2277,  0.0300,  0.1652],
        [ 0.0179, -0.0853, -0.1347,  0.0778],
        [-0.2140, -0.1866, -0.2502, -0.0905],
        [ 0.1818, -0.0901, -0.3024, -0.0216],
        [ 0.2330, -0.0778, -0.1988,  0.0321],
        [ 0.3542, -0.0150, -0.1095, -0.2148],
        [ 0.4449, -0.6226,  0.0155, -0.1254],
        [ 0.0902, -0.0166, -0.2563,  0.0569],
        [ 0.2688, -0.2110,  0.1150,  0.1995],
        [ 0.1270, -0.0994,  0.0290,  0.0276],
        [-0.0216, -0.2380,  0.1288,  0.2761]], device='cuda:0',
       grad_fn=\<AddmmBackward\>)
**Platform**

Device: NVIDIA GeForce GTX 1080 Ti
OS: Ubuntu 16.04.6 LTS
CUDA version: 11.4
NCCL version: 2.7.8
PyTorch version: 1.8.0

**Comment by laekov** [comment]
The test is wrong. We will fix this. Thank you for your careful inspection.
