### ISSUE TITLE
How to use Convolution operator as the expert?

### ISSUE THREAD

**Issue by hobbitlzy** [laekov/fastmoe#121]
Hi, I am trying to train an convolution-backbone network with MoE. There are two difficulties encountered. The first difficulty is that current API seems unable to directly use. The [parameter](https://github.com/laekov/fastmoe/blob/9a01f8fa466a56e225d56a18304c6675084cc3fd/fmoe/layers.py#L109) of class FMoE requires the hidden dimension, but the convolution layer actually does not define the hidden dimension explicity.

Then, I find the FMoE class cannot accept tensor with dimension greater than 2. Therefore, I guess I cannot directly pass the image (with shape N, C, H, W) into the layer? My code snippet is 
```
from fmoe.layers import FMoE
import torch
from fmoe.gates import NaiveGate,SwitchGate
N=3
num_expert=2

hidden_size=5
out_feature=4
layer=torch.nn.Linear(in_features=hidden_size,out_features=out_feature).to("cuda")
layer.weight=torch.nn.Parameter(torch.ones_like(layer.weight))
my_moe=FMoE(num_expert=num_expert,d_model=hidden_size,top_k=1,expert=layer,gate=SwitchGate).to("cuda")
inputs=torch.rand((N,1,hidden_size)).to("cuda")
print(my_moe(inputs))

```
Here I use the linear layer as the expert just to test the input dimension. The error information is
```
Traceback (most recent call last):
  File "/home/zyli/fastmoe/try.py", line 15, in <module>
    print(my_moe(inputs))
  File "/home/zyli/anaconda3/envs/QMoE/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zyli/fastmoe/fmoe/layers.py", line 241, in forward
    experts=self.experts
  File "/home/zyli/fastmoe/fmoe/layers.py", line 78, in _fmoe_general_global_forward
    outp = tree.map_structure(gather_func, x)
  File "/home/zyli/anaconda3/envs/QMoE/lib/python3.7/site-packages/tree/__init__.py", line 430, in map_structure
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/zyli/anaconda3/envs/QMoE/lib/python3.7/site-packages/tree/__init__.py", line 430, in <listcomp>
    [func(*args) for args in zip(*map(flatten, structures))])
  File "/home/zyli/fastmoe/fmoe/layers.py", line 75, in gather_func
    world_size,
  File "/home/zyli/fastmoe/fmoe/functions.py", line 171, in forward
    maybe_overlap=False)
  File "/home/zyli/fastmoe/fmoe/functions.py", line 89, in _local_gather
    inp_buf.index_copy_(0, pos, inp)
IndexError: index_copy_(): When source and destination are not scalars, their dimensionality must match. Source dimensionality (3), destination dimensionality (2)
```

One possible solution I think is to first apply img2col to the input so that the convolution is transformed to matrix multiplication, but this incurs oblivious overhead. Or I need to modify the implementation of the class FMoE. Both of them are not elegant, so is there any idea to do this?

**Comment by laekov** [comment]
For non-2d input, you are supposed to reshape it to 2d. For example, for a tensor of `NCHW`, you should reshape it into `N(CHW)`, so that FMoE can dispatch the input features correctly. You can reshape it back after the MoE layer, and in the expert function.

There is another issue in your code. You are supposed to feed a layer generator (taking the hidden size as an input parameter) instead of a layer instance. The following modified version works well at my place.

```python
from fmoe.layers import FMoE
import torch
from fmoe.gates import NaiveGate,SwitchGate
N=3
num_expert=2

def gen_my_layer(hidden_size):
    layer=torch.nn.Linear(in_features=hidden_size,out_features=out_feature)
    layer.weight=torch.nn.Parameter(torch.ones_like(layer.weight))
    return layer

hidden_size=5
out_feature=4
my_moe=FMoE(num_expert=num_expert,
        d_model=hidden_size,
        top_k=1,
        expert=gen_my_layer,
        gate=SwitchGate).to("cuda")
inputs=torch.rand((N,1,hidden_size)).to("cuda").reshape(N, hidden_size)
print(my_moe(inputs))
```

**Comment by hobbitlzy** [comment]
Thanks😁! I get your point. BTW, FMoE does not have the document yet?

**Comment by laekov** [comment]
No, we don't have a detailed document for every function, yet.

**Comment by hobbitlzy** [comment]
I am wondering why the `expert` passed into the FMoE() needs to be a generator? In my code, I actually changed the source code of FMoE class so that I take a pytorch module as the expert. Will this lead to some dangers?

**Comment by laekov** [comment]
Because I didn't see an elegant way to copy a torch module instances for multiple experts. Therefore, we require the `expert` argument to be a generator. (This is actually documented in the in-line document of FMoE class)

In fact, if you want to directly use module instances as experts, you can pass `None` to the `FMoE` ctor, and then specify the `experts`   attribute explicitly, like we have in the `FMoETransformerMLP` class.

**Comment by laekov** [comment]
I don't think this is elegant enough. Using deepcopy makes the experts implicitly initialized the same, which may be problematic. And this makes no difference from manually setting `moe_layer.experts = nn.ModuleList([copy...])`, which users have better understanding of what is happening.

**Comment by hobbitlzy** [comment]
You are right. I see your consideration🤔. Thanks again😁.

**Comment by Qianshaowei** [comment]
> There is another issue in your code. You are supposed to feed a layer generator (taking the hidden size as an input parameter) instead of a layer instance. The following modified version works well at my place.

您好，我复制了这份代码来测试所安装的fastmoe环境，发现这段代码运行不起来，报错如下：
`
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    print(my_moe(inputs))
  File "/usr/local/python3.7.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.1/lib/python3.7/site-packages/fastmoe-1.1.0-py3.7-linux-x86_64.egg/fmoe/layers.py", line 254, in forward
    experts=self.experts
  File "/usr/local/python3.7.1/lib/python3.7/site-packages/fastmoe-1.1.0-py3.7-linux-x86_64.egg/fmoe/layers.py", line 61, in _fmoe_general_global_forward
    x = expert_fn(x, fwd_expert_count)
  File "/usr/local/python3.7.1/lib/python3.7/site-packages/fastmoe-1.1.0-py3.7-linux-x86_64.egg/fmoe/layers.py", line 178, in expert_fn
    outputs.append(self.experts[i](inp_slice, torch.tensor([fwd_expert_count[i]])))
  File "/usr/local/python3.7.1/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 3 were given
`

**Comment by Peg-Wu** [comment]
@Qianshaowei 
I met  the same issue, did you solve it?

**Comment by Qianshaowei** [comment]
> @Qianshaowei I met the same issue, did you solve it?

好像是专家forward()需要传入两个参数，如果要使用FMoE

**Comment by Peg-Wu** [comment]
@Qianshaowei 是的，我将代码进行了如下修改：
```python
import torch
import torch.nn as nn
import torch.nn.functional as F
from fmoe.layers import FMoE
from fmoe.gates import NaiveGate

word_size = 1
num_expert = 8
top_k = 2
batch_size = 256
d_model = 128
device = torch.device("cuda:0")

class My_Expert(nn.Module):
    def __init__(self, d_model, hidden_size=1024):
        super().__init__()
        self.fc1 = nn.Linear(d_model, hidden_size)
        self.fc2 = nn.Linear(hidden_size, d_model)

    def forward(self, x, *args):  # *args is necessary
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x

model = FMoE(num_expert=num_expert,
             world_size=word_size,
             top_k=top_k,
             d_model=d_model,
             expert=My_Expert,
             gate=NaiveGate)

model = model.to(device)
               
# (batch_size, d_model)  
x = torch.rand(batch_size, d_model)  # Notice: input must be 2 dimensions.
x = x.to(device)
print(model(x).shape)
```

但是我遇到了新的问题，似乎当cuda:0内存不足时无法运行，我将模型和输入转移到其他卡上也会出现cuda out of memory的问题，你看一下上面的脚本可以运行嘛?
