### ISSUE TITLE
module 'fmoe_cuda' has no attribute 'ensure_nccl'

### ISSUE THREAD

**Issue by Fangbo0506** [laekov/fastmoe#124]
fmoe_cuda.ensure_nccl

module 'fmoe_cuda' has no attribute 'ensure_nccl'

**Comment by laekov** [comment]
I don't think this can happen with current version of FastMoE. Please provide more details, e.g. your version of FastMoE and a detailed call stack, so that we can look into this issue.

**Comment by jinggaizi** [comment]
hi, i also meet the problem, it's because building without USE_NCCL=1. however, when i add it and rebuild, some error like "error: ‘c10d’ has not been declared“ happend, i found c10d in torch/lib and it's linked when building, how can i sovle this problem

**Comment by laekov** [comment]
@jinggaizi again, please provide us with your version of FastMoE and PyTorch.

**Comment by jinggaizi** [comment]
sorry, it's my fault, i built fmoe in https://github.com/tencent-ailab/3m-asr/tree/main/fastmoe, it's version 0.1.2 and made some modifications, when in build v1.0.0, it's work, i will check the different by 3m-asr
