### ISSUE TITLE
The top_k in Gshard seems to be one.

### ISSUE THREAD

**Issue by Fragile-azalea** [laekov/fastmoe#129]
**Describe the bug**
Hi, I find that the top_k in Gshard seems to be one. I wonder if this is the expected result. Thank you.

**To Reproduce**
1. USE_NCCL=1 python setup.py install
2. cd test && MASTER_PORT=12355 python test_gates.py 

**Logs**

https://github.com/laekov/fastmoe/blob/f2e0d1d5b2885cb058dcdd17aba90a50e7d8c9e7/fmoe/gates/gshard_gate.py#L24
```
print(topk_idx.shape[0], gate_score.shape[0], top_k)
16 16 1
```

**Platform**
- Device: GeForce RTX 2080Ti * 4
- OS: Linux gpu9 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- CUDA version: 10.2
- NCCL version: 2.7.8-1
- PyTorch version: 1.9.1
- Python Version: 3.8

**Comment by laekov** [comment]
This seems to be a bug. It is expected to deduce `top_k` by the shape of the indices and the batch size. It should be `top_k = topk_idx.numel() // gate_score.shape[0]`

**Comment by Fragile-azalea** [comment]
> This seems to be a bug. It is expected to deduce `top_k` by the shape of the indices and the batch size. It should be `top_k = topk_idx.numel() // gate_score.shape[0]`

How about using self.top_k directly?

**Comment by laekov** [comment]
> > This seems to be a bug. It is expected to deduce `top_k` by the shape of the indices and the batch size. It should be `top_k = topk_idx.numel() // gate_score.shape[0]`
> 
> How about using self.top_k directly?

That makes sense :sweat_smile:
