### ISSUE TITLE
During inference, I need to run forward on CPU, so FMOE does not support CPU inference now?

### ISSUE THREAD

**Issue by snsun** [laekov/fastmoe#131]
This is because you did not move the model and the input to CUDA, while FastMoE only supports computation on CUDA.

The following code should work.

```python
import torch
from fmoe.transformer import FMoETransformerMLP

x = torch.rand(64, 64).cuda()
model = FMoETransformerMLP().cuda()
y = model(x)
```

_Originally posted by @laekov in https://github.com/laekov/fastmoe/issues/73#issuecomment-919672644_

**Comment by laekov** [comment]
We do not have a CPU version for distributed CPU inference, yet. Besides, the `FMoELinear` layer which computes multiple linear layers at the same time is specifically designed for GPUs.

So, if you want to do inference on CPU, you can only run the model using a single process, and you have to bypass the `FMoELinear` layer using the interface for customized experts in `FMoE` class.

**Comment by laekov** [comment]
Closing due to lack of further response. Feel free to re-open if you have any progress.
