### ISSUE TITLE
CUBLAS_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by Irenehere** [laekov/fastmoe#134]
**Describe the bug**
When the model  begins to train, I come up with the following error:

**Logs**

 > done building sapmles index maping
 > saved the index mapping in models/bert/my-bert_text_sentence_test_indexmap_20mns_512msl_0.10ssp_1234s.npy
 > elasped time to build and save samples mapping (seconds): 0.000438
 > loading indexed mapping from models/bert/my-bert_text_sentence_test_indexmap_20mns_512msl_0.10ssp_1234s.npy
    loaded indexed file in 0.000 seconds
    total number of samples: 204
> finished creating BERT datasets ...
[after dataloaders are built] datetime: 2022-09-09 08:42:57 
done with setups ...
time (ms) | model and optimizer: 8546.43 | train/valid/test data iterators: 227.91
training ...
[before the start of training step] datetime: 2022-09-09 08:42:57 
CUDA error at /home/jovyan/data/tmp/fastmoe-megatron-patch/cuda/moe_compute_kernel.cu:132 code=8(CUBLAS_STATUS_ARCH_MISMATCH) "cublasXgemm( smgr->handle(i), CUBLAS_OP_T, CUBLAS_OP_N, out_feat, expert_count[i], in_feat, &alpha, weight + i * in_feat * out_feat, in_feat, input_buf + ptr * in_feat, in_feat, &beta, output_buf + out_feat * ptr, out_feat )" 

**Platform**
 - Device: [e.g. NVIDIA V100]
 - CUDA version: [11.1]
 - NCCL version: [2.8.3]
 - PyTorch version: [1.8]
 - fastmoe version: [0.1.2]

Any idea about this problem?

**Comment by laekov** [comment]
According to [NVIDIA's document](https://docs.nvidia.com/cuda/cublas/index.html), 

> The function requires a feature absent from the device architecture; usually caused by compute capability lower than 5.0.

I suppose that when compiling FastMoE, cuda's architecture flag is not specified properly, or your cuBLAS library's version mismatches the one for your GPU.

**Comment by laekov** [comment]
Closing due to lack of further response. Feel free to re-open if you have any progress.
