### ISSUE TITLE
Does FastMoe have a plan to support pipeline parallel with Megatron?

### ISSUE THREAD

**Issue by LitLeo** [laekov/fastmoe#139]
Does FastMoe have a plan to support pipeline parallel with Megatron?

Or is it possible to do this? Can you give me some guidance?

**Comment by laekov** [comment]
We have already had that in our `v0.2.1` releasae. Our current Megatron adaptor works with pipeline parallelism without extra modification.

**Comment by laekov** [comment]
Closing due to lack of further response. Feel free to re-open if you have any progress.
