### ISSUE TITLE
Compatible version of Megatron-LM

### ISSUE THREAD

**Issue by zjujh1995** [laekov/fastmoe#14]
"FastMoE currently works with both v2.0 and v2.1 release of Megatron-LM."
May I ask where can I find the v2.0/v2.1 version of Megatron? To my knowledge, the newest version of Megatron in pypi is 1.15, and I can't find any information about versions in its git project, neither.

**Comment by xptree** [comment]
You can find them at https://github.com/NVIDIA/Megatron-LM/tags.
