### ISSUE TITLE
Is it necessary to use the synchronize operation after the allreduce operation here?

### ISSUE THREAD

**Issue by Fragile-azalea** [laekov/fastmoe#143]
Hello author, I would like to ask if it is necessary to use the synchronize operation after the allreduce operation. Does the synchronize operation synchronize all GPUs?
https://github.com/laekov/fastmoe/blob/9303ac18c16987db130b9d7ddfcd096e363df7d2/fmoe/distributed.py#L70-L71

**Comment by laekov** [comment]
`torch.cuda.synchronize` synchronizes all used GPUs of the current process. As `torch.distributed` launches nccl kernels on the default stream, I think it is not that necessary to synchronize here.
