### ISSUE TITLE
Outdated doc for smart schedule with num_expert > 1?

### ISSUE THREAD

**Issue by chenyu-jiang** [laekov/fastmoe#166]
**Describe the bug**
The document on ["faster performance features"](https://github.com/laekov/fastmoe/tree/master/doc/fastermoe) says `num_expert` has to be 1 for smart scheduling, while #146 seems to have added support for `num_expert > 1`.

**To Reproduce**
N/A

**Expected behavior**
The document to be updated.

**Logs**
N/A

**Platform**
N/A

**Additional context**
N/A

**Comment by zms1999** [comment]
Yes, you are right. I will modify the document.
