### ISSUE TITLE
could it be supported for Tensorflow ?

### ISSUE THREAD

**Issue by ericxsun** [laekov/fastmoe#17]

**Comment by laekov** [comment]
No. 
PyTorch is somehow strongly coupled with FastMoE. Support for TF requires rewrinting more than half of the code.
If you are interested in using FastMoE in TF, contributions are appreciated.

**Comment by xptree** [comment]
@ericxsun If you are looking for existing MoE implementation based on TF.

You may want to refer to 
https://github.com/tensorflow/lingvo/blob/master/lingvo/tasks/lm/README.md
https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/moe.py

**Comment by ericxsun** [comment]
@xptree thansk very much
