### ISSUE TITLE
MOELinear is much slower than torch.nn.Linear

### ISSUE THREAD

**Issue by kamanphoebe** [laekov/fastmoe#178]
**Describe the bug**
I am trying to fmoefy a ViT-Base by replacing the MLP layers with `FMoETransformerMLP`. However, it took nearly 10x longer time than the ViT-Base for the resulted model (let's call it VMoE-Base) to train one epoch. Inspecting the time consumption using the PyTorch profiler, I found that MOELinear takes up most of the duration:

![image](https://github.com/laekov/fastmoe/assets/46671628/d75fbb0b-6c1d-4db8-9a60-dcc38539b563)

I wrote a simple testing script as follows to further check about this. The `CUDA time total` results are 10us and 97us for `mlp` and `moe` respectively. It may be a bit unfair to directly compare these two values as there are more operations within `FMoETransformerMLP`. Yet the gap is unacceptably huge. This seems abnormal, did I miss something important?
```python
from fmoe.transformer import FMoETransformerMLP
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity

x = torch.randn(2).cuda()

mlp = nn.Sequential(
    nn.Linear(2, 2), # mimicking the gate
    nn.Linear(2, 8), # htoh4
    nn.GELU(),
    nn.Linear(8, 2)  # h4toh
).cuda()

moe = FMoETransformerMLP(1, 2, 8, top_k=1).cuda()

with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
    out = mlp(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10)) # CUDA time total: 10us

with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
    out = moe(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10)) # CUDA time total: 97us
```

**Platform**
 - NCCL version: I built fastmoe with `USE_NCCL=0`, not sure whether it affects.
 - CUDA version: 12.1
 - PyTorch version: 2.1.0

**Comment by laekov** [comment]
I am not sure what happened in your profiling results. However, your reproducing script uses undersized modules that are not suitable for testing performance of GPUs. I modified it as follows, and it performs as expected on my machine with a V100. Can you please try it on your machine and see if there is still a large gap?

```python
from fmoe.transformer import FMoETransformerMLP
import torch
import torch.nn as nn
from torch.profiler import profile, record_function, ProfilerActivity


bs = 4 * 1024
d_model = 2048
d_hidden = 8192
n_expert = 1
x = torch.randn(bs, d_model).cuda()

mlp = nn.Sequential(
    # nn.Linear(d_model, n_expert), # mimicking the gate
    nn.Linear(d_model, d_hidden), # htoh4
    nn.GELU(),
    nn.Linear(d_hidden, d_model)  # h4toh
).cuda()

moe = FMoETransformerMLP(n_expert, d_model, d_hidden, top_k=1).cuda()

with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
    out = mlp(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10)) # CUDA time total: 23ms

with profile(activities=[ProfilerActivity.CUDA], record_shapes=True) as prof:
    out = moe(x)
print(prof.key_averages().table(sort_by="cuda_time_total", row_limit=10)) # CUDA time total: 24ms
```

**Comment by kamanphoebe** [comment]
Thanks for the quick response! I ran your code and the results are similar to yours.

I will write a simplified script later regarding my complete training pipeline and try figuring out the reason of slow running. I will come back to you if necessary.

Thank you again for the assistance :)

**Comment by kamanphoebe** [comment]
Hi,

I finally find the reason of the training time difference between ViT-B and VMoE-B. The large gap appears only when the Automatic Mixed Precision (AMP) package of PyTorch is used during training. It seems that AMP is not able to cast `FMoETransformerMLP` to fp16 and hence longer operation time for the MoE model. 

Is there any way to make `FMoETransformerMLP` compatible with the autocasting of AMP? I did find a [pull request](https://github.com/laekov/fastmoe/pull/150) discussing a related topic, but it only modified FastMoE to adapt to inputs in different data types instead of converting the weights.

**Comment by laekov** [comment]
I didn't use FastMoE with AMP. @santurini can you please share your experience on using AMP with FastMoE?

**Comment by santurini** [comment]
Unfortunately to use AMP with FMoE you have to cast the inputs back to fp32, doing the other way around would've messed too much with the CUDA code. You can do this by modifying this line in [fmoe/linear.py](https://github.com/santurini/fastmoe/blob/master/fmoe/linear.py), row 73:
```
  def forward(self, inp, fwd_expert_count):
      r"""
      Call MOE function
      """
      x = MOELinear.apply(inp.float(), fwd_expert_count, self.weight, self.bias)
      return x
```

I was able to use AMP this way without having troubles, probably your problem depends on the input size or the training code. @laekov, could it depend also by the fact he's on single GPU?

**Comment by kamanphoebe** [comment]
Thank you for your reply! Actually my complete training code for FMoE model is able to run with AMP, but the operations within FMoE modules remain to be fp32. Therefore, I am curious about whether FMoE operations can also participate in autocasting. According to your experience, FMoE modules can only deal with fp32 so far. Did I understand correctly?

**Comment by santurini** [comment]
Yes, exactly! You can try [this](https://github.com/laekov/fastmoe/issues/178#issuecomment-1807880375) and see if there is still a significant drop in the performance. Of course you'll have to recompile the library.
