### ISSUE TITLE
prep_text8.py没有该脚本

### ISSUE THREAD

**Issue by PowerDispatch** [laekov/fastmoe#190]
没有该脚本

![image](https://github.com/laekov/fastmoe/assets/158788585/34c60eee-be96-4615-adbf-5269f9ff3dc1)

**Comment by laekov** [comment]
这部分代码来源于 [transformer-xl](https://github.com/kimiyoung/transformer-xl). 由于我们只使用了该仓库中的 enwiki8 作为示例, 故没有对其它模块进行支持. 如需使用, 您可以参考其原仓库.
