### ISSUE TITLE
Support a detailed install introduction

### ISSUE THREAD

**Issue by starhiking** [laekov/fastmoe#24]
I wanna try your exciting work, but I have toubled in installation.
Could you please give me a detailed steps for set up? like all dependences with verison in requirements.txt and so on.

**Comment by laekov** [comment]
We do hava a more detailed tutorial with docker in our homepage at <https://fastmoe.ai/documentation/get-started.html>. 

You may also join the slack group and ask for help there. We helped quite a few guys with installation on slack.
 
btw, @Sengxian can u plz put the from-scratch installation tutorial on the homepage?

**Comment by Sengxian** [comment]
> We do hava a more detailed tutorial with docker in our homepage at https://fastmoe.ai/documentation/get-started.html.
> 
> You may also join the slack group and ask for help there. We helped quite a few guys with installation on slack.
> 
> btw, @Sengxian can u plz put the from-scratch installation tutorial on the homepage?

Done
