### ISSUE TITLE
How can I fmoefy a BERT properly?

### ISSUE THREAD

**Issue by zjujh1995** [laekov/fastmoe#26]
Like what you have done in fmoefying GPT with Megatron, I tried to fmoefy a BERT model. However, the model I got didn't outperform the baseline BERT. Loss curves of BERT w & w/o are just similar.

May I ask if you have tried to fmoefy a BERT successfully? Do we need to make some additional modification for this? Thanks a lot!

**Comment by laekov** [comment]
We also observed the similar situation. We are working on this. Plz let us know if you have any further findings.

**Comment by ymjiang** [comment]
> We also observed the similar situation. We are working on this. Plz let us know if you have any further findings.

Hi, is there any update on this issue?

**Comment by laekov** [comment]
> > We also observed the similar situation. We are working on this. Plz let us know if you have any further findings.
> 
> Hi, is there any update on this issue?

Not yet.
