### ISSUE TITLE
Hi, an error occurs when i install with USE_NCCL=1:

### ISSUE THREAD

**Issue by BinHeRunning** [laekov/fastmoe#28]
Hi, an error occurs when i install with USE_NCCL=1:

RuntimeErrorRuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:825, unhandled system error, NCCL version 2.7.8
ncclSystemError: System call (socket, malloc, munmap, etc) failed.

Env:
1. torch 1.8
2. cuda 10.2
3. nccl 2.7.8

Has anyone had a similar problem ?

_Originally posted by @BinHeRunning in https://github.com/laekov/fastmoe/issues/16#issuecomment-817601869_

**Comment by Sengxian** [comment]
See #27
