### ISSUE TITLE
When we say coverges faster, why we use the first 60K steps rather than time? 

### ISSUE THREAD

**Issue by Carolingliang** [laekov/fastmoe#30]
FastMoE-GPT coverges faster than GPT in the first 60K steps of training loss,  when we say coverges faster, why we use the first 60K steps rather than time?
In my experiment, in the first 3 hours,  GPT coverges faster than FastMoE-GPT:joy:

**Comment by laekov** [comment]
We think achieving lower loss is more important than saving a little training time.

**Comment by Carolingliang** [comment]
使用fmoe加大参数量导致的loss降低与改变参数导致的loss降低优势效果并不明显啊，
我使用fmoe加大的参数量到P与改变layers等参数加大参数量到P实验结果相比，按照你们的思路，第二种方法随着iter增加loss下降的更快，所以为啥要用fmoe而不是直接改变参数呢
其次，我看moe论文，moe是目的是实现条件计算的，也没提随着iter的增加loss的收敛快慢啊？







At 2021-04-26 11:33:01, "Rick Ho" ***@***.***> wrote:

We think achieving lower loss is more important than saving a little training time.
