### ISSUE TITLE
Does fastmoe support distributed training with multiple machine?

### ISSUE THREAD

**Issue by ododoyo** [laekov/fastmoe#33]
Hi there,

I have installed the `fastmoe` and the model with distributed experts can be trained successfully in single machine. However, when the experts are distributed on multiple machine, the torch.distributed subprocess will die with `<Signals.SIGSEGV: 11>`. Have you experimented `fastmoe` in distributed training with multiple machine?

many thanks~

**Comment by laekov** [comment]
I tested fastmoe on up to 8 machines without such problem. Can you provide some details on your environment and how you execute your script on multiple machines?

**Comment by ododoyo** [comment]
I test it with  torch1.7+ cuda10.1 + nccl2.7.8
- the python version is 3.7 and managed by anaconda
- torch is installed by `pip install`
- nccl lib path is added and fastmoe is installed by `USE_NCCL=1 python setup.py install`.
- The gcc/g++ version is 7.3.1
Maybe there is something wrong with my environment.  Should it be the inconsistency of gcc version used to compile the pytorch and fastmoe?

**Comment by ododoyo** [comment]
I test it with torch1.7+cuda10.1+nccl2.7.8
 - python version is 3.7 and managed by anaconda
 - torch is installed by pip
 - nccl lib path is added and fastmoe is installed by `USE_NCCL=1 python setup.py install` with gcc/g++7.3.1

I modified fastmoe code for customized use by just adding some arguments for functions. The modified distributed.py is only conducted with torch.distributed package.

maybe there is something wrong with my environment. would it be the inconsistency of gcc version used to compile pytorch and fastmoe? should I install pytorch from source with gcc of the same version?

**Comment by laekov** [comment]
I do not recognize anything strange from your describe in your environment. Does it run correctly within one machine? Can you try if simply initializing `torch.distributed` works across machines in your environment?

**Comment by ododoyo** [comment]
I think the fastmoe model trained with one machine works well and the `torch.distributed` is also fine across machine. I will rebuild my environment same with yours and try it again.
Thanks for your replies~

**Comment by laekov** [comment]
I get reminded that fastmoe v0.1.1 does have bugs running with nccl across machines, and it is fixed in v0.1.2. Is your fastmoe v0.1.1 or v0.1.2?

**Comment by ododoyo** [comment]
The version of installed fastmoe is v0.1.2. 

I have just solved the problem by switching environment to pytorch1.8+cuda10.2+nccl2.7.8.  Maybe it's the cuda10.1 leading to the failure.

Thanks for your help!
