### ISSUE TITLE
Expert capacity

### ISSUE THREAD

**Issue by david-macleod** [laekov/fastmoe#34]
Hi 

I was just wondering if the fastmoe implementation uses the concept of expert capacity as described by the Switch Transformer paper? In other words if we have 8 tokens, 4 experts the expert capacity would be 2 (without considering the capacity factor). So in this scenario if more than 2 tokens gets assigned to a given expert does the token get dropped as in the Switch Transformer formulation? Or does it still get processed in fastmoe?

**Comment by laekov** [comment]
This function is still being developed. It will not get processed, similiar to switch, in our design.

**Comment by david-macleod** [comment]
OK thanks for the quick reply!
