### ISSUE TITLE
magic number (256) in CUDA functions

### ISSUE THREAD

**Issue by zjujh1995** [laekov/fastmoe#35]
There is a magic number (256) in Both in CUDA functions `moe_cuda_local_scatter_impl` and `moe_cuda_local_gather_impl`. I cannot understand what it means and not sure if it's a potential bug in fastmoe. Is it related to the parameters of hardwares?

Related codes:
`batch_scatter_kernel<scalar_t> 
<<<batch_size, 256, 0, smgr->stream(0)>>>(in_feat, d_pos, input, input_buf); `

**Comment by xptree** [comment]
You can find the meaning of this number in any cuda programming tutorial, e..g. https://developer.nvidia.com/blog/easy-introduction-cuda-c-and-c/. The number defines how many device threads execute the kernel in parallel.
