### ISSUE TITLE
Are the MoE CPM-2 and GLM released Wudao 2.0 trained with FastMoE?

### ISSUE THREAD

**Issue by MuyangDu** [laekov/fastmoe#43]
I've read the paper of [CPM-2](https://github.com/TsinghuaAI/CPM-2) and [GLM](https://github.com/THUDM/GLM) and found that both of them have MoE version.  I checked their repo but didn't find anything related to FastMoE. So I'm wondering whether the MoE CPM and GLM are trained with FastMoE since all of them are release together in Wudao 2.0. Thanks!

**Comment by xptree** [comment]
The current release of GLM is a dense model without MoE.

As for CPM-2, it would better to ask the authors about their implementation details.

Thanks.
