### ISSUE TITLE
How to use fastmoe on fairseq?

### ISSUE THREAD

**Issue by Hanlard** [laekov/fastmoe#53]
If we want to use fastmoe on fairseq, which parts need to be rewritten?

**Comment by laekov** [comment]
We have not tried that. If your purpose is to try BASE layers (arxiv 2103.16716), all you need is a new gate module that implements the distribution algorithm in the paper.

**Comment by Hanlard** [comment]
> all you need is a new gate module that implements the distribution algorithm in the paper.

Thanks, I modified the code of the MLP layer, and the training (Gshard and Naive gate) loss indeed converged faster than the original transformer in the fairseq library.

But, I find whether if I add the gate loss to total loss, the model performance (logPPL in translation) won't change.

## [code]:
GateLoss=([layer.MoeMLP.gate.loss for layer in self.encoder.layers],[layer.MoeMLP.gate.loss for layer in self.decoder.layers])

The logPPL and Gate loss curves can be seen in the following pictures. 
![image](https://user-images.githubusercontent.com/44184184/123188778-30fae580-d4cf-11eb-8fc0-947c6d3a1748.png)
![image](https://user-images.githubusercontent.com/44184184/123188951-8505ca00-d4cf-11eb-8340-7c474e831dca.png)

**Comment by Hanlard** [comment]
for p in module.parameters():
    setattr(p, "expert", "I'm an expert.")
FairSeq的All-reduce也会跳过专家层。所以给专家参数设置一个"expert"属性就可以进行distributed moe x data parallel 混合并行了。

**Comment by laekov** [comment]
GShard and Naive gates performs differently, according to my observation. I hear from someone else that the AUX loss is not workign well in every model. Maybe you need to make some changes to the algorithm to make it work?
