### ISSUE TITLE
PyPI Package

### ISSUE THREAD

**Issue by ClashLuke** [laekov/fastmoe#72]
Could you push FastMoE to PyPI?\
As a workaround, we're currently using `git+https://github.com/laekov/fastmoe` in our `requirements.txt`, but a proper pip integration would be very much appreciated.

**Comment by laekov** [comment]
In fact, we have considered this before we release the first version. But we faced an issue that as FastMoE depends on PyTorch, CUDA and NCCL, there are too many combinations of them if we want to provide binary packages via pypi.

Do you or does anyone have any ideas on this? Looking forward for help.

**Comment by laekov** [comment]
> You're right, that might cause some issues.
> DeepSpeed simply ignored a large part of these dependencies and put a note in the readme. Would this be a "solution" here?

This does not sound elegant to me. For example, we act differently when compiling our C code with different versions of PyTorch. So, there should definately be different versions of FastMoE binary according to PyTorch version. That is why I still insist that the users should compile FastMoE in their own environment. Anyway, NVIDIA's apex also requires users to compile locally.

I suppose an elegant way should be creating a script to automatically compile and pack FastMoE with the combinations of dependents. We may use [spack](https://github.com/spack/spack) to handle different versions of python, cuda, and NCCL. But I still do not have an idea about how to deal with different PyTorch versions. I am not quite motivated to dig deep into this, and looking for contribution from the open source community.
