### ISSUE TITLE
Instability While Training Transformer-XL with FastMoE

### ISSUE THREAD

**Issue by latifisalar** [laekov/fastmoe#74]
Hi there,

I have been running experiments with FastMoE implementation on Transformer-XL, however the gradients overflow while using mixed-precision and dynamic loss scaling option.

Here are the settings of the training:

- Base Transformer-XL (12 layers)
- enwik8 dataset
- Number of experts: 16
- fp16 and dynamic loss scaling
- The remaining parameters are the default ones as `run_enwik8_base_moe.sh`

Output:
```
| epoch  24 step   185600 |   3900 batches | lr 0.000139 | ms/batch 659.04 | loss  0.65 | bpc   0.93429
| epoch  24 step   185800 |   4100 batches | lr 0.000139 | ms/batch 658.89 | loss  0.65 | bpc   0.94323
Gradient overflow.  Skipping step, reducing loss scale to 16384.0
Gradient overflow.  Skipping step, reducing loss scale to 8192.0
Gradient overflow.  Skipping step, reducing loss scale to 4096.0
...
Gradient overflow.  Skipping step, reducing loss scale to 3.16e-322
Gradient overflow.  Skipping step, reducing loss scale to 1.6e-322
Gradient overflow.  Skipping step, reducing loss scale to 8e-323
Gradient overflow.  Skipping step, reducing loss scale to 4e-323
Gradient overflow.  Skipping step, reducing loss scale to 2e-323
Gradient overflow.  Skipping step, reducing loss scale to 1e-323
Gradient overflow.  Skipping step, reducing loss scale to 5e-324
Gradient overflow.  Skipping step, reducing loss scale to 0.0
Traceback (most recent call last):
ZeroDivisionError: float division by zero
```

Here is my system setup:
- 4 GPUs
- Pytorch 1.7
- CUDA 11.1.0
- NCCL 2.7.8

I was wondering whether you have faced a similar issue in your experiments.

Thanks!

**Comment by laekov** [comment]
I suppose the input data and the weight there directly lead to overflow in forward pass, which cannot be handled by loss scaling. @xptree @Sengxian can u plz have a look on this?

**Comment by xptree** [comment]
@latifisalar  We have not met this before. Have you solved this problem? Or what is the behavior of FP32 training?

**Comment by latifisalar** [comment]
@xptree Not yet, the problem is still in place and it happens for both enwik8 and wt103 dataset. I am using FP32 for now which trains without an issue.
