### ISSUE TITLE
安装成功后在test文件夹下测试出现的问题

### ISSUE THREAD

**Issue by Sakura-rain** [laekov/fastmoe#77]
你好，我在安装好后在test文件中进行测试的时候出现了一些问题，希望您能提供一些帮助。
1、在运行test文件夹内的测试文件时，如果使用多卡，会出现如下的问题
![12c0b350f5ab94bba88fe741faab7f1](https://user-images.githubusercontent.com/55499068/135229689-df66b098-c7d9-4d88-b26f-ef196a7373bb.png)

2、请问moe是否有单测或者citest的脚本可以参考，在运行tests多卡的时候出现了一些问题
使用命令： mpirun -np 2 ./test.sh test_gate.py

**Comment by laekov** [comment]
1. test.sh 未能正确识别 mpi 传入的环境变量. 建议检查 mpi 版本及脚本里读出来的 rank.
2. test 目录下可以使用 pytest 进行单元测试.

**Comment by Sakura-rain** [comment]
> 1. test.sh 未能正确识别 mpi 传入的环境变量. 建议检查 mpi 版本及脚本里读出来的 rank.
> 2. test 目录下可以使用 pytest 进行单元测试.
![LL35R JV2$D5SW}5DF2AOZP](https://user-images.githubusercontent.com/55499068/135233521-b4bdfaa8-7519-45c4-bd7f-ed08c29920ba.png)
请问这个有问题吗

**Comment by laekov** [comment]
> > 1. test.sh 未能正确识别 mpi 传入的环境变量. 建议检查 mpi 版本及脚本里读出来的 rank.
> > 2. test 目录下可以使用 pytest 进行单元测试.
> >    ![LL35R JV2$D5SW}5DF2AOZP](https://user-images.githubusercontent.com/55499068/135233521-b4bdfaa8-7519-45c4-bd7f-ed08c29920ba.png)
> >    请问这个有问题吗

看起来是对的. 检查一下 12215 端口是否被其它程序占用了? (比如之前没杀干净) 也可以用 `MASTER_PORT` 环境变量手工换一个端口.

**Comment by Sakura-rain** [comment]
> > > 1. test.sh 未能正确识别 mpi 传入的环境变量. 建议检查 mpi 版本及脚本里读出来的 rank.
> > > 2. test 目录下可以使用 pytest 进行单元测试.
> > >    ![LL35R JV2$D5SW}5DF2AOZP](https://user-images.githubusercontent.com/55499068/135233521-b4bdfaa8-7519-45c4-bd7f-ed08c29920ba.png)
> > >    请问这个有问题吗
> 
> 看起来是对的. 检查一下 12215 端口是否被其它程序占用了? (比如之前没杀干净) 也可以用 `MASTER_PORT` 环境变量手工换一个端口.

好的，谢谢了
