### ISSUE TITLE
Confusion in the paper [FastMoE: A Fast Mixture-of-Expert Training System]

### ISSUE THREAD

**Issue by feifeibear** [laekov/fastmoe#85]
Dear authors,
I like your project and find it is very useful. I am reading your paper and trying to catch some basic concepts in MOE.
However, I have some confusion in the paper.
1. Figure 4. should input 5 be sent to expert 2, according to the gate output? In the paper, it is sent to the expert 0.
2. Page 6, you mentioned the load balance problem. Was it solved in this project? or it is inherent in the model parallelism.

**Comment by laekov** [comment]
1. Sorry for the mistake. It should be sent to expert 0, or the last number of the gate output should be `2`.
2. We have introduced GShard and Switch's policy in FastMoE v0.2, which provides better load balance. The gate API is also open to developers to develop customized balanced gate modules.
