### ISSUE TITLE
Program got Signal SIGSEGV if use tensor parallelism with FastMoE in Megatron after patching the clip_grads.py

### ISSUE THREAD

**Issue by VisionTheta** [laekov/fastmoe#98]
**Describe the bug**

Program got signal 11 (SIGSEGV) if we apply tensor parallelism with FastMoE in Megatron code after patching the clip_grads.py

**To Reproduce**

1. Apply the fastmoe patch `fmoefy-v2.2.patch` and `clip-grad-v2.2.patch` to Megatron code v2.2
2. Run `examples/pretrain_gpt_distributed_with_mp.sh`, with the configuration as follows:
```bash
# only listed the modified parameters
GPUS_PER_NODE=8
NNODES=1

       --tensor-model-parallel-size 4 \
       --pipeline-model-parallel-size 1 \
       --fmoefy \
       --num-experts 8 \
```
3. after fews minutes, will get the error. Logs are stated in **Logs** section.,

**Logs**
If applicable, add logs to help explain your problem.

```bash
Traceback (most recent call last):
  File "xxx/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "xxx/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "xxx/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "xxx/fastmoe/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "xxx/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/xxx/fastmoe/bin/python', '-u', 'pretrain_gpt.py', '--local_rank=7', '--tensor-model-parallel-size', '4', '--pipeline-model-parallel-size', '1', '--num-layers', '24', '--hidden-size', '1024', '--num-attention-heads', '16', '--micro-batch-size', '4', '--global-batch-size', '16', '--seq-length', '1024', '--max-position-embeddings', '1024', '--train-iters', '500000', '--lr-decay-iters', '320000', '--save', '...', '--data-impl', 'mmap', '--split', '949,50,1', '--distributed-backend', 'nccl', '--lr', '0.00015', '--lr-decay-style', 'cosine', '--min-lr', '1.0e-5', '--weight-decay', '1e-2', '--clip-grad', '1.0', '--lr-warmup-fraction', '.01', '--checkpoint-activations', '--log-interval', '100', '--save-interval', '10000', '--eval-interval', '1000', '--eval-iters', '10', '--fp16', '--fmoefy', '--num-experts', '8']' died with <Signals.SIGSEGV: 11>.
```

**Platform**
 - Device: 1 Node * (V100 32G * 8)
 - OS: Ubuntu 16.04
 - CUDA version: 10.2
 - NCCL version: 2.7.8
 - PyTorch version: 1.8.0

**Additional context**
1. FastMoE can work with dp, dp+pp, but not dp+tp+pp if we apply those two patches.

2. If we only apply `fmoefy-v2.2.py`, then dp+tp+pp will work. But I'm afraid the gradient normalization will be wrong?

**Comment by laekov** [comment]
I wonder if `grads_in_moe` being empty will cause this trouble. Can you try add some empty tensor check in the patched code, and see if works?

**Comment by VisionTheta** [comment]
Yes, that may be the problem. I didn't try more parameters, but got the following result:

```
dp:2 + tp:4 + pp:1 with 8 expert: len(grads_in_moe) is 0 on rank 1,2,3,5,6,7, and len(grads_in_moe) is 96 on rank 0,4 
dp:2 + tp:2 + pp:2 with 8 expert: len(grads_in_moe) is 0 on rank 1,3,5,7, and len(grads_in_moe) is 48 on rank 0,2,4,6 
```

**Comment by laekov** [comment]
Yeah, then I suppose we should skip the synchronization (and `multi_tensor_apply`) for ranks where `len(grads_in_moe) == 0`

**Comment by VisionTheta** [comment]
Thanks a lot. But before modifying the code, I need to figure out gradient update mechanism in the MoE part.
